name: mywealthplan
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - panel
  - numpy
  - hvplot
  - python=3.9
  - pip
  - matplotlib
  - bokeh
  - jupyterlab
  - awswrangler
  - boto3
  - python-dotenv
  - pip:
      - appdirs==1.4.4
      - bs4==0.0.1
      - cssselect==1.2.0
      - fake-useragent==1.1.1
      - feedparser==6.0.10
      - lxml==4.9.2
      - parse==1.19.0
      - pyee==8.2.2
      - pyppeteer==1.0.2
      - pyquery==2.0.0
      - requests-html==0.10.0
      - sgmllib3k==1.0.0
      - w3lib==2.1.1
      - websockets==10.4
      - yahoo-fin==0.8.9.1

